<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class PrakiraanCuacasTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('prakiraan_cuacas')->delete();
        
        \DB::table('prakiraan_cuacas')->insert(array (
            0 => 
            array (
                'id' => 1,
                'kecamatan' => 'Kecamatan Amahai',
                'tanggal' => '2026-04-18',
                'jam' => '00.00',
                'cuaca' => 'Berawan',
                'suhu' => 26,
                'kelembaban' => 82,
                'angin_arah' => 'B',
                'angin_kecepatan' => 12,
                'icon' => '☁️',
                'created_at' => '2026-04-18 01:09:44',
                'updated_at' => '2026-04-18 01:09:44',
            ),
            1 => 
            array (
                'id' => 2,
                'kecamatan' => 'Kecamatan Amahai',
                'tanggal' => '2026-04-18',
                'jam' => '06.00',
                'cuaca' => 'Cerah Berawan',
                'suhu' => 27,
                'kelembaban' => 75,
                'angin_arah' => 'BD',
                'angin_kecepatan' => 15,
                'icon' => '⛅',
                'created_at' => '2026-04-18 01:09:44',
                'updated_at' => '2026-04-18 01:09:44',
            ),
            2 => 
            array (
                'id' => 3,
                'kecamatan' => 'Kecamatan Amahai',
                'tanggal' => '2026-04-18',
                'jam' => '12.00',
                'cuaca' => 'Cerah',
                'suhu' => 33,
                'kelembaban' => 65,
                'angin_arah' => 'D',
                'angin_kecepatan' => 20,
                'icon' => '☀️',
                'created_at' => '2026-04-18 01:09:44',
                'updated_at' => '2026-04-18 01:09:44',
            ),
            3 => 
            array (
                'id' => 4,
                'kecamatan' => 'Kecamatan Amahai',
                'tanggal' => '2026-04-18',
                'jam' => '18.00',
                'cuaca' => 'Berawan',
                'suhu' => 30,
                'kelembaban' => 72,
                'angin_arah' => 'BD',
                'angin_kecepatan' => 10,
                'icon' => '☁️',
                'created_at' => '2026-04-18 01:09:44',
                'updated_at' => '2026-04-18 01:09:44',
            ),
            4 => 
            array (
                'id' => 5,
                'kecamatan' => 'Kecamatan Amahai',
                'tanggal' => '2026-04-18',
                'jam' => '24.00',
                'cuaca' => 'Hujan Ringan',
                'suhu' => 25,
                'kelembaban' => 88,
                'angin_arah' => 'U',
                'angin_kecepatan' => 8,
                'icon' => '🌧️',
                'created_at' => '2026-04-18 01:09:44',
                'updated_at' => '2026-04-18 01:09:44',
            ),
            5 => 
            array (
                'id' => 6,
                'kecamatan' => 'Kecamatan Banda',
                'tanggal' => '2026-04-18',
                'jam' => '00.00',
                'cuaca' => 'Hujan Sedang',
                'suhu' => 24,
                'kelembaban' => 90,
                'angin_arah' => 'BL',
                'angin_kecepatan' => 18,
                'icon' => '🌧️',
                'created_at' => '2026-04-18 01:09:44',
                'updated_at' => '2026-04-18 01:09:44',
            ),
            6 => 
            array (
                'id' => 7,
                'kecamatan' => 'Kecamatan Banda',
                'tanggal' => '2026-04-18',
                'jam' => '06.00',
                'cuaca' => 'Berawan',
                'suhu' => 25,
                'kelembaban' => 84,
                'angin_arah' => 'B',
                'angin_kecepatan' => 14,
                'icon' => '☁️',
                'created_at' => '2026-04-18 01:09:44',
                'updated_at' => '2026-04-18 01:09:44',
            ),
            7 => 
            array (
                'id' => 8,
                'kecamatan' => 'Kecamatan Banda',
                'tanggal' => '2026-04-18',
                'jam' => '12.00',
                'cuaca' => 'Cerah Berawan',
                'suhu' => 31,
                'kelembaban' => 70,
                'angin_arah' => 'D',
                'angin_kecepatan' => 22,
                'icon' => '⛅',
                'created_at' => '2026-04-18 01:09:44',
                'updated_at' => '2026-04-18 01:09:44',
            ),
            8 => 
            array (
                'id' => 9,
                'kecamatan' => 'Kecamatan Banda',
                'tanggal' => '2026-04-18',
                'jam' => '18.00',
                'cuaca' => 'Hujan Ringan',
                'suhu' => 28,
                'kelembaban' => 80,
                'angin_arah' => 'BL',
                'angin_kecepatan' => 12,
                'icon' => '🌧️',
                'created_at' => '2026-04-18 01:09:44',
                'updated_at' => '2026-04-18 01:09:44',
            ),
            9 => 
            array (
                'id' => 10,
                'kecamatan' => 'Kecamatan Banda',
                'tanggal' => '2026-04-18',
                'jam' => '24.00',
                'cuaca' => 'Berawan Tebal',
                'suhu' => 24,
                'kelembaban' => 87,
                'angin_arah' => 'U',
                'angin_kecepatan' => 10,
                'icon' => '☁️',
                'created_at' => '2026-04-18 01:09:44',
                'updated_at' => '2026-04-18 01:09:44',
            ),
            10 => 
            array (
                'id' => 11,
                'kecamatan' => 'Kecamatan Tehoru',
                'tanggal' => '2026-04-18',
                'jam' => '00.00',
                'cuaca' => 'Cerah',
                'suhu' => 27,
                'kelembaban' => 70,
                'angin_arah' => 'T',
                'angin_kecepatan' => 10,
                'icon' => '☀️',
                'created_at' => '2026-04-18 01:09:44',
                'updated_at' => '2026-04-18 01:09:44',
            ),
            11 => 
            array (
                'id' => 12,
                'kecamatan' => 'Kecamatan Tehoru',
                'tanggal' => '2026-04-18',
                'jam' => '06.00',
                'cuaca' => 'Cerah',
                'suhu' => 29,
                'kelembaban' => 65,
                'angin_arah' => 'TD',
                'angin_kecepatan' => 12,
                'icon' => '☀️',
                'created_at' => '2026-04-18 01:09:44',
                'updated_at' => '2026-04-18 01:09:44',
            ),
            12 => 
            array (
                'id' => 13,
                'kecamatan' => 'Kecamatan Tehoru',
                'tanggal' => '2026-04-18',
                'jam' => '12.00',
                'cuaca' => 'Cerah Berawan',
                'suhu' => 34,
                'kelembaban' => 58,
                'angin_arah' => 'D',
                'angin_kecepatan' => 18,
                'icon' => '⛅',
                'created_at' => '2026-04-18 01:09:44',
                'updated_at' => '2026-04-18 01:09:44',
            ),
            13 => 
            array (
                'id' => 14,
                'kecamatan' => 'Kecamatan Tehoru',
                'tanggal' => '2026-04-18',
                'jam' => '18.00',
                'cuaca' => 'Cerah Berawan',
                'suhu' => 31,
                'kelembaban' => 66,
                'angin_arah' => 'TD',
                'angin_kecepatan' => 14,
                'icon' => '⛅',
                'created_at' => '2026-04-18 01:09:44',
                'updated_at' => '2026-04-18 01:09:44',
            ),
            14 => 
            array (
                'id' => 15,
                'kecamatan' => 'Kecamatan Tehoru',
                'tanggal' => '2026-04-18',
                'jam' => '24.00',
                'cuaca' => 'Cerah',
                'suhu' => 26,
                'kelembaban' => 72,
                'angin_arah' => 'T',
                'angin_kecepatan' => 8,
                'icon' => '☀️',
                'created_at' => '2026-04-18 01:09:44',
                'updated_at' => '2026-04-18 01:09:44',
            ),
            15 => 
            array (
                'id' => 16,
                'kecamatan' => 'Kecamatan Seram Utara',
                'tanggal' => '2026-04-18',
                'jam' => '00.00',
                'cuaca' => 'Berawan',
                'suhu' => 25,
                'kelembaban' => 80,
                'angin_arah' => 'U',
                'angin_kecepatan' => 11,
                'icon' => '☁️',
                'created_at' => '2026-04-18 01:09:44',
                'updated_at' => '2026-04-18 01:09:44',
            ),
            16 => 
            array (
                'id' => 17,
                'kecamatan' => 'Kecamatan Seram Utara',
                'tanggal' => '2026-04-18',
                'jam' => '06.00',
                'cuaca' => 'Hujan Ringan',
                'suhu' => 24,
                'kelembaban' => 86,
                'angin_arah' => 'BL',
                'angin_kecepatan' => 16,
                'icon' => '🌧️',
                'created_at' => '2026-04-18 01:09:44',
                'updated_at' => '2026-04-18 01:09:44',
            ),
            17 => 
            array (
                'id' => 18,
                'kecamatan' => 'Kecamatan Seram Utara',
                'tanggal' => '2026-04-18',
                'jam' => '12.00',
                'cuaca' => 'Berawan',
                'suhu' => 31,
                'kelembaban' => 72,
                'angin_arah' => 'T',
                'angin_kecepatan' => 19,
                'icon' => '☁️',
                'created_at' => '2026-04-18 01:09:44',
                'updated_at' => '2026-04-18 01:09:44',
            ),
            18 => 
            array (
                'id' => 19,
                'kecamatan' => 'Kecamatan Seram Utara',
                'tanggal' => '2026-04-18',
                'jam' => '18.00',
                'cuaca' => 'Cerah Berawan',
                'suhu' => 29,
                'kelembaban' => 74,
                'angin_arah' => 'TD',
                'angin_kecepatan' => 13,
                'icon' => '⛅',
                'created_at' => '2026-04-18 01:09:44',
                'updated_at' => '2026-04-18 01:09:44',
            ),
            19 => 
            array (
                'id' => 20,
                'kecamatan' => 'Kecamatan Seram Utara',
                'tanggal' => '2026-04-18',
                'jam' => '24.00',
                'cuaca' => 'Hujan Ringan',
                'suhu' => 24,
                'kelembaban' => 89,
                'angin_arah' => 'BL',
                'angin_kecepatan' => 9,
                'icon' => '🌧️',
                'created_at' => '2026-04-18 01:09:44',
                'updated_at' => '2026-04-18 01:09:44',
            ),
            20 => 
            array (
                'id' => 21,
                'kecamatan' => 'Kecamatan Masohi',
                'tanggal' => '2026-04-18',
                'jam' => '00.00',
                'cuaca' => 'Hujan Lebat',
                'suhu' => 23,
                'kelembaban' => 95,
                'angin_arah' => 'B',
                'angin_kecepatan' => 28,
                'icon' => '⛈️',
                'created_at' => '2026-04-18 01:09:44',
                'updated_at' => '2026-04-18 01:09:44',
            ),
            21 => 
            array (
                'id' => 22,
                'kecamatan' => 'Kecamatan Masohi',
                'tanggal' => '2026-04-18',
                'jam' => '06.00',
                'cuaca' => 'Hujan Sedang',
                'suhu' => 24,
                'kelembaban' => 90,
                'angin_arah' => 'BL',
                'angin_kecepatan' => 22,
                'icon' => '🌧️',
                'created_at' => '2026-04-18 01:09:44',
                'updated_at' => '2026-04-18 01:09:44',
            ),
            22 => 
            array (
                'id' => 23,
                'kecamatan' => 'Kecamatan Masohi',
                'tanggal' => '2026-04-18',
                'jam' => '12.00',
                'cuaca' => 'Berawan Tebal',
                'suhu' => 28,
                'kelembaban' => 82,
                'angin_arah' => 'BD',
                'angin_kecepatan' => 20,
                'icon' => '☁️',
                'created_at' => '2026-04-18 01:09:44',
                'updated_at' => '2026-04-18 01:09:44',
            ),
            23 => 
            array (
                'id' => 24,
                'kecamatan' => 'Kecamatan Masohi',
                'tanggal' => '2026-04-18',
                'jam' => '18.00',
                'cuaca' => 'Hujan Ringan',
                'suhu' => 26,
                'kelembaban' => 86,
                'angin_arah' => 'B',
                'angin_kecepatan' => 15,
                'icon' => '🌧️',
                'created_at' => '2026-04-18 01:09:44',
                'updated_at' => '2026-04-18 01:09:44',
            ),
            24 => 
            array (
                'id' => 25,
                'kecamatan' => 'Kecamatan Masohi',
                'tanggal' => '2026-04-18',
                'jam' => '24.00',
                'cuaca' => 'Berawan',
                'suhu' => 24,
                'kelembaban' => 88,
                'angin_arah' => 'U',
                'angin_kecepatan' => 11,
                'icon' => '☁️',
                'created_at' => '2026-04-18 01:09:44',
                'updated_at' => '2026-04-18 01:09:44',
            ),
        ));
        
        
    }
}